import './globals.css';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { getValidatedEnv } from '@/config/env';
import { QueryProvider } from '@/providers/QueryProvider';
import { TestWalletProvider } from '@/providers/TestWalletProvider';
import { ThemeProvider } from '@/providers/ThemeProvider';
import { WagmiProvider } from '@/providers/WagmiProvider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const env = getValidatedEnv();

  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <style>{`
html {
  font-family: ${geistSans.style.fontFamily};
  --font-sans: ${geistSans.variable};
  --font-mono: ${geistMono.variable};
}
        `}</style>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <WagmiProvider env={env}>
            <QueryProvider>
              <TestWalletProvider>{children}</TestWalletProvider>
            </QueryProvider>
          </WagmiProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
